spring:
  datasource:
    url: jdbc:h2:mem:ordering;MODE=MYSQL;INIT=CREATE SCHEMA IF NOT EXISTS \"public\"
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      hibernate:
        type: trace
      springframework:
        orm:
          jpa:
            JpaTransactionManager: debug
productCatalog:
  file:
    path: product-catalog.xml