spring:
  datasource:
    url: jdbc:mysql://db:3306/restbucks_ordering?useUnicode=true&characterEncoding=utf-8
    username: ordering
    password:
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: none
      ejb:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
logging:
  level:
    org:
      hibernate:
        type: trace
      springframework:
        orm:
          jpa:
            JpaTransactionManager: debug
productCatalog:
  file:
    path: product-catalog.xml