spring:
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: none
      ejb:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
logging:
  level:
    org:
      hibernate:
        type: trace
      springframework:
        orm:
          jpa:
            JpaTransactionManager: debug
productCatalog:
  file:
    path: product-catalog.xml